[package]
name = "puma_os"
version = "0.1.0"
authors = ["Jamin Menter <jaminmenter@gmail.com>"]
edition = "2018"

[dependencies]
bootloader = "0.3.12"
volatile = "0.2.3"

[package.metadata.bootimage]
default-target = "x86_64-puma_os.json"